### ISSUE TITLE
Add php-intl to the php extension

### ISSUE THREAD

**Issue by IkiaeM** [Sigma-Production/ptero-eggs#30]
Add php-intl to the php extension. (Required for LiteBans-php site [mincraft plugin])

https://gitlab.com/ruany/litebans-php/-/wikis/Installation

<img width="757" alt="Capture d’écran 2022-11-26 à 18 53 02" src="https://user-images.githubusercontent.com/64362443/204102344-19c03c02-42ab-4ae9-8906-d26bbdf6d723.png">

**Comment by finnie2006** [comment]
I will look into this soon

**Comment by joeecodes** [comment]
any update on this?

**Comment by finnie2006** [comment]
Try our new docker image
``hcr.io/sigma-production/nginx-ptero:8.1``

**Comment by FairGames** [comment]
> ghcr.io/sigma-production/nginx-ptero:8.1

fixed thanks
