### ISSUE TITLE
/entrypoint.sh: line 11: start.sh: not found

### ISSUE THREAD

**Issue by mrranger** [Sigma-Production/ptero-eggs#31]
Pulling from finnie2006/nginx-ptero 
Status: Image is up to date for ghcr.io/finnie2006/nginx-ptero:latest 
Digest: sha256:333ae8f3ab88b589f09a9d409da0e3640f8622fa1f3438099d3e8d41422ae2ce 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ start.sh
/entrypoint.sh: line 11: start.sh: not found
container@pterodactyl~ Server marked as running...
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by finnie2006** [comment]
You are using an older version off the egg
