### ISSUE TITLE
entrypoint.sh: line 4: syntax error: unexpected "then"

### ISSUE THREAD

**Issue by SpikyTV** [Sigma-Production/ptero-eggs#34]
Pulling from finnie2006/nginx-ptero 
Status: Image is up to date for ghcr.io/finnie2006/nginx-ptero:8.1 
Digest: sha256:135a7f450f4ff0ff5352934b3a649e3a5086101dacdf5301feacc927c17b0b16 
Finished pulling Docker container image
/entrypoint.sh: eval: line 4: syntax error: unexpected "then"
:/home/container$

**Comment by koenhawkins11** [comment]
I am getting the same error let me know if you find a fix to it please

**Comment by finnie2006** [comment]
It seems like there is something wrong with the startup command not sure what though

**Comment by finnie2006** [comment]
For now you could change the startup command to {{STARTUP_CMD}};

**Comment by finnie2006** [comment]
The problem should be fixed, let me know if it works

**Comment by finnie2006** [comment]
Closing the issue, if the issue persists repon the issue
