### ISSUE TITLE
env: can't execute 'php': No such file or directory

### ISSUE THREAD

**Issue by Johno95CZ** [Sigma-Production/ptero-eggs#37]
When I try to install some composer modules I always get this error -> env: can't execute 'php': No such file or directory
Even tried to reinstall whole server on pterodactyl. Any tips how to fix this?

**Comment by 404invalid-user** [comment]
what composer modules are you trying to install? it looks like they are trying to call php maybe as a setup script, it instead needs to specify the full path I'm not too sure what this is or even if a cli version of php is in the docker image
