### ISSUE TITLE
just a lil confused

### ISSUE THREAD

**Issue by ThegdogTwitch** [Sigma-Production/ptero-eggs#40]
so yes i have this panel, ect.  got this egg.  ported it 8080 cause pt wont let me just do 80.  goto my ip and with a index.html get file not found or 403 forbidden.  im new to this whole thing and tyring to learn and have learned very quickly.  any help and clear up will be greatly appreciated as im doing all this on my own

**Comment by BasToTheMax** [comment]
Did you put the index.html file in the `webroot` directory?

**Comment by finnie2006** [comment]
Correct answer has been given
