### ISSUE TITLE
Missing XMLWriter PHP extension

### ISSUE THREAD

**Issue by penalte** [Sigma-Production/ptero-eggs#44]
Hello this is an important extension can you add it to the docker image?

Thank you.

**Comment by xGranolah** [comment]
also need them

**Comment by itsjustnickdev** [comment]
@finnie2006 ^

**Comment by finnie2006** [comment]
It should be included

**Comment by itsjustnickdev** [comment]
![afbeelding](https://github.com/user-attachments/assets/6148c20e-7662-4cc8-97a5-67818e4d7003)
@finnie2006

**Comment by finnie2006** [comment]
In the latest docker image i added the xmlwriter extension, can you let me know if it works as expected?
```ghcr.io/sigma-production/nginx-ptero:8.3```

**Comment by finnie2006** [comment]
Seems like i forgot to change a path will fix it, i will let it know

**Comment by finnie2006** [comment]
Updated the docker image, restart should fix it @itsjustnickdev
