### ISSUE TITLE
[Issue] Cant stop server without terminating it

### ISSUE THREAD

**Issue by Steephydra393** [Sigma-Production/ptero-eggs#48]
When I select "Stop" or "Restart" in the petrodactyl panel, It does nothing. I have to terminate the server in order to restart it.

**Comment by Saketh9033** [comment]
It is actually a bug to fix that you need to have admin access
 
1: Go to nest in which egg is present.
2: Select egg.
3: In the **configuration** tab scroll down.
4: You have to change **Stop Command** from _^C _ to _^C & ^C_.
5: Now save the egg you are done.
<img width="882" alt="image" src="https://cdn.discordapp.com/attachments/996770390435168276/1116377365266841682/image.png">

**Comment by finnie2006** [comment]
Fixed in latest commit
