### ISSUE TITLE
Wordpress not connecting to database

### ISSUE THREAD

**Issue by MihaiCiornei** [Sigma-Production/ptero-eggs#72]
When i try to configure the Wordpress , is not connecting to database service.
The panel is working , sa mariadb is working well.
I'm preaty sure to have the database created, and user to . I check it . 

Pls can some one tell me how can i solve this?

**Comment by Tiebienotjuh** [comment]
Please turn on wordpress debug mode by adding this to your wp-config.php 
`
define('WP_DEBUG', true);
`

When you enabled debug mode, please try again and post the log file in this issue.

**Comment by finnie2006** [comment]
Closed due to long inactivity, reopen if issue persits
